services:
  - type: web
    name: my-php-app
    env: php
    plan: free
    runtime: php
    rootDir: .
    envVars:
      - key: PHP_VERSION
        value: 8.1
    startCommand: vendor/bin/heroku-php-apache2 public/
